# Generated by Django 4.2.4 on 2023-08-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/img')),
            ],
        ),
    ]
