# Generated by Django 4.2.4 on 2023-08-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessages',
            new_name='ServiceMessage',
        ),
    ]
