# Generated by Django 4.2.4 on 2023-08-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_contactmessages_servicemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
