# Generated by Django 4.2.4 on 2023-08-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_blogpost_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='name',
            new_name='name1',
        ),
    ]
