# Generated by Django 4.2.4 on 2023-08-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_name_blogpost_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='name1',
        ),
    ]
